name: cron release
on:
  schedule:
    - cron: '52 9 * * 3'
  workflow_dispatch:

jobs:
  update-rulesets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: mmdb/Country.mmdb
