name: cron release
on:
  schedule:
    - cron: '52 9 * * 3'
  workflow_dispatch:

jobs:
  update-rulesets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
            mmdb/Country.mmdb
